niter: 1000
seed: 1

# dimension of embedding
d: 5
# batchsize
batchsize: 128

nlayer: 1

enumerate_all_classes: true
p0: 0.7
p1: 0.9
p2: 0.7
p3: 0.5

use_WkWq: false 
use_ffn: true
use_residue: true

normalize_embed_shift: false
normalize_embed_scale: false

opt:
  method: "adam"
  lr: 0.1
  momentum: 0.9
  wd: 5e-4