seed: 0
# String, can be a number, or a multiplication of multiple numbers, e.g., 2x3x4, 
# which corresponds to Abelian group Z_2 x Z_3 x Z_4
M: "127"
hidden_size: 512
learning_rate: 0.001

# Adam or sgd
optim: adam 

# sqr or relu
activation: sqr 
num_epochs: 3000
test_size: 0.7
weight_decay: 1e-4
use_bn: false

# nll or mse
loss_func: "nll"
save_interval: 1000
init_save_range: 200
eval_interval: 100
normalize: false

set_weight_reg : 1e-3

scale_down_top: false

load_dataset_split : null
load_initial_layerab : null

post_process: false

# If true, it will adjust the test_size accordingly.
use_critical_ratio: false
# If use critical ratio is true, then test_size = 1 - (critical_ratio_multiplier - critical_ratio_delta) * log(M) / M 
critical_ratio_delta: 0
critical_ratio_multiplier: 2.7482

other_layers: 0
group_type: "modular_addition"

group_collection_max_dk: 0
